package com.omnigocrm
import android.app.*
import android.content.Intent
import android.net.Uri
import android.os.Bundle
import android.graphics.Color
import android.view.Gravity
import android.widget.*
import java.util.concurrent.Executors
class MainActivity:Activity(){
 private lateinit var api:ApiClient;private lateinit var session:SessionManager;private lateinit var root:LinearLayout;private val pool=Executors.newCachedThreadPool()
 override fun onCreate(b:Bundle?){super.onCreate(b);api=ApiClient(this);session=SessionManager(this);if(session.token==null)login()else dashboard()}
 private fun login(){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;gravity=Gravity.CENTER;setPadding(32,48,32,48)};box.addView(tv("OmniGoCRM",28,true));val e=EditText(this).apply{hint="Email"};val p=EditText(this).apply{hint="Password";inputType=129};val b=Button(this).apply{text="Sign in"};box.addView(e);box.addView(p);box.addView(b);setContentView(box);b.setOnClickListener{pool.execute{try{api.login(e.text.toString(),p.text.toString());runOnUiThread{dashboard()}}catch(x:Exception){runOnUiThread{toast(x.message?:"Login failed")}}}}}
 private fun shell(title:String):LinearLayout{root=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setBackgroundColor(Color.rgb(247,249,252))};val head=LinearLayout(this).apply{setPadding(12,12,12,8)};head.addView(tv(title,22,true),LinearLayout.LayoutParams(0,-2,1f));val out=Button(this).apply{text="Logout"};head.addView(out);out.setOnClickListener{api.logout();session.clear();login()};root.addView(head);val nav=LinearLayout(this).apply{orientation=LinearLayout.HORIZONTAL};listOf("Dashboard","Leads","Contacts","Customers","Companies","Tasks","Follow-ups","Products","Quotations","Orders","Payments","Notifications").forEach{n->val b=Button(this).apply{text=n};nav.addView(b);b.setOnClickListener{when(n){"Dashboard"->dashboard();"Leads"->leads();"Contacts"->contacts();"Customers"->customers();"Companies"->companies();"Tasks"->tasks();"Follow-ups"->followups();"Products"->products();"Quotations"->quotations();"Orders"->orders();"Payments"->payments();"Notifications"->notifications()}}};root.addView(HorizontalScrollView(this).apply{addView(nav)});val sc=ScrollView(this);sc.addView(LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(14,14,14,40)});root.addView(sc,LinearLayout.LayoutParams(-1,0,1f));setContentView(root);return root}
 private fun body()=(root.getChildAt(2) as ScrollView).getChildAt(0) as LinearLayout
 private fun dashboard(){shell("Dashboard");pool.execute{try{val d=api.dashboard();val c=d.getJSONObject("counts");runOnUiThread{body().addView(tv("Leads "+c.optInt("leads")+" • Contacts "+c.optInt("contacts")+" • Customers "+c.optInt("customers"),18,true));body().addView(tv("Open follow-ups: "+c.optInt("followups"),16,false))}}catch(e:Exception){runOnUiThread{toast(e.message?:"Dashboard error")}}}}
 private fun leads(){shell("Leads");val add=Button(this).apply{text="+ New Lead"};body().addView(add);add.setOnClickListener{newLead()};pool.execute{try{api.leads().forEach{l->runOnUiThread{body().addView(card(l.firstName+" "+l.lastName,l.company+" • "+l.mobile+" • "+l.status){lead(l.id)})}}}catch(e:Exception){runOnUiThread{toast(e.message?:"Leads error")}}}}
 private fun newLead(){shell("New Lead");val f=edit("First name");val l=edit("Last name");val c=edit("Company");val m=edit("Mobile");val r=edit("Requirement");listOf(f,l,c,m,r).forEach{body().addView(it)};val b=Button(this).apply{text="Create lead"};body().addView(b);b.setOnClickListener{pool.execute{try{api.createLead(f.text.toString(),l.text.toString(),c.text.toString(),m.text.toString(),r.text.toString());runOnUiThread{leads()}}catch(e:Exception){runOnUiThread{toast(e.message?:"Create failed")}}}}}
 private fun lead(id:Long){shell("Lead");pool.execute{try{val o=api.lead(id);runOnUiThread{body().addView(tv(o.optString("first_name")+" "+o.optString("last_name"),25,true));body().addView(tv(o.optString("company")+"\n"+o.optString("mobile")+"\n"+o.optString("requirement"),16,false));val call=Button(this).apply{text="Call"};val wa=Button(this).apply{text="WhatsApp"};val cv=Button(this).apply{text="Convert to Contact"};body().addView(call);body().addView(wa);body().addView(cv);val phone=o.optString("whatsapp").ifBlank{o.optString("mobile")};call.setOnClickListener{dial("lead",id,phone)};wa.setOnClickListener{openWa("lead",id)}}}catch(e:Exception){runOnUiThread{toast(e.message?:"Lead error")}}}}
 private fun contacts(){shell("Contacts");pool.execute{try{api.contacts().forEach{c->runOnUiThread{body().addView(card(c.firstName+" "+c.lastName,c.company+" • "+c.mobile))}}}catch(e:Exception){runOnUiThread{toast(e.message?:"Contacts error")}}}}
 private fun customers(){shell("Customers");pool.execute{try{api.customers().forEach{c->runOnUiThread{body().addView(card(c.code,c.name+" • "+c.company+" • "+c.mobile))}}}catch(e:Exception){runOnUiThread{toast(e.message?:"Customers error")}}}}
 private fun companies(){shell("Companies");pool.execute{try{api.companies().forEach{c->runOnUiThread{body().addView(card(c.name,c.phone+" • "+c.email))}}}catch(e:Exception){runOnUiThread{toast(e.message?:"Companies error")}}}}
 private fun tasks(){shell("Tasks");pool.execute{try{api.tasks().forEach{t->runOnUiThread{body().addView(card(t.title,t.priority+" • "+t.status+" • "+t.dueAt){if(t.status!="completed")pool.execute{try{api.completeTask(t.id);runOnUiThread{tasks()}}catch(e:Exception){runOnUiThread{toast(e.message?:"Task error")}}}})}}catch(e:Exception){runOnUiThread{toast(e.message?:"Tasks error")}}}}
 private fun products(){shell("Products & Services");pool.execute{try{val a=api.products();for(i in 0 until a.length()){val o=a.getJSONObject(i);runOnUiThread{body().addView(card(o.optString("name"),"₹"+o.optString("price")+" / "+o.optString("unit")))}}}catch(e:Exception){runOnUiThread{toast(e.message?:"Products error")}}}}
 private fun quotations(){shell("Quotations");pool.execute{try{val a=api.quotations();for(i in 0 until a.length()){val o=a.getJSONObject(i);runOnUiThread{body().addView(card(o.optString("quote_number"),"₹"+o.optString("total")+" • "+o.optString("status")))}}}catch(e:Exception){runOnUiThread{toast(e.message?:"Quotations error")}}}}
 private fun orders(){shell("Orders");pool.execute{try{val a=api.orders();for(i in 0 until a.length()){val o=a.getJSONObject(i);runOnUiThread{body().addView(card(o.optString("order_number"),"₹"+o.optString("total")+" • "+o.optString("status")))}}}catch(e:Exception){runOnUiThread{toast(e.message?:"Orders error")}}}}
 private fun payments(){shell("Payments");pool.execute{try{val a=api.payments();for(i in 0 until a.length()){val o=a.getJSONObject(i);runOnUiThread{body().addView(card("₹"+o.optString("amount"),o.optString("method")+" • "+o.optString("paid_at")))}}}catch(e:Exception){runOnUiThread{toast(e.message?:"Payments error")}}}}
 private fun notifications(){shell("Notifications");pool.execute{try{val a=api.notifications();for(i in 0 until a.length()){val o=a.getJSONObject(i);runOnUiThread{body().addView(card(o.getString("data"),o.optString("created_at")){if(!o.optBoolean("read_at"))pool.execute{try{api.readNotification(o.optString("id"));runOnUiThread{notifications()}}catch(e:Exception){runOnUiThread{toast(e.message?:"Notification error")}}}})}}}catch(e:Exception){runOnUiThread{toast(e.message?:"Notifications error")}}}}
 private fun followups(){shell("Follow-ups");pool.execute{try{val a=api.followUps();for(i in 0 until a.length()){val o=a.getJSONObject(i);runOnUiThread{body().addView(card("Follow-up",o.optString("scheduled_for")+" • "+o.optString("status")))}}catch(e:Exception){runOnUiThread{toast(e.message?:"Follow-up error")}}}}
 private fun openWa(type:String,id:Long){pool.execute{try{val url=api.whatsapp(type,id,"follow_up");runOnUiThread{startActivity(Intent(Intent.ACTION_VIEW,Uri.parse(url)))}}catch(e:Exception){runOnUiThread{toast(e.message?:"WhatsApp error")}}}}
 private fun dial(type:String,id:Long,phone:String){if(phone.isBlank()){toast("No phone");return};try{startForegroundService(Intent(this,CallRecordingService::class.java).putExtra("subject_type",type).putExtra("subject_id",id).putExtra("phone",phone))}catch(_:Exception){};startActivity(Intent(Intent.ACTION_DIAL,Uri.parse("tel:"+phone.filter{it.isDigit()||it=='+'})))}
 private fun tv(s:String,size:Float,b:Boolean)=TextView(this).apply{text=s;textSize=size;if(b)setTypeface(null,1);setPadding(0,8,0,8)}
 private fun edit(h:String)=EditText(this).apply{hint=h;setPadding(12,12,12,12)}
 private fun card(t:String,sub:String,click:(()->Unit)?=null)=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(14,12,14,12);setBackgroundColor(Color.WHITE);addView(tv(t,17,true));addView(tv(sub,14,false));click?.let{setOnClickListener{it()}};layoutParams=LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,6,0,6)}}
 private fun toast(s:String)=Toast.makeText(this,s,Toast.LENGTH_LONG).show()
}