{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "omnigocrm.fullname" . }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ default (randAlphaNum 32) .Values.postgres.password | quote }}
  JWT_SECRET: {{ default (randAlphaNum 64) .Values.jwtSecret | quote }}
{{- end }}
