import React,{useEffect,useMemo,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";

const API=import.meta.env.VITE_API_URL??"/api/v1";

async function api(path,opt={},token){
  const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json",...(token?{Authorization:"Bearer "+token}:{}),...(opt.headers||{})}});
  const d=await r.json().catch(()=>({}));
  if(!r.ok)throw Error(d.error||"Request failed");
  return d;
}

const nav=[
  ["dashboard","⌂","Dashboard"],["leads","♙","Leads"],["contacts","♙","Contacts"],["accounts","▣","Companies"],
  ["opportunities","◉","Opportunities"],["quotes","▤","Quotes"],["orders","▱","Orders"],["invoices","▧","Invoices"],
  ["products","◇","Products"],["tasks","✓","Tasks"],["calendar","□","Calendar"],["automation","⌘","Automation"],
  ["conversations","✉","Email & SMS"],["reports","◔","Reports"],["settings","⚙","Settings"]
];

const resourceMap={
  contacts:["Contacts","Contact"],accounts:["Companies","Company"],opportunities:["Opportunities","Opportunity"],
  quotes:["Quotes","Quote"],orders:["Orders","Order"],invoices:["Invoices","Invoice"],products:["Products","Product"],
  tasks:["Tasks","Task"],conversations:["Email & SMS","Conversation"]
};

function Login({done}){
  const[m,setM]=useState(false);const[f,setF]=useState({name:"",email:"",password:"",workspaceName:""});const[e,setE]=useState("");
  return <div className="auth"><form className="auth-card" onSubmit={async x=>{x.preventDefault();setE("");try{const r=await api("/auth/"+(m?"register":"login"),{method:"POST",body:JSON.stringify(f)});localStorage.setItem("token",r.token);done(r.token)}catch(x){setE(x.message)}}}>
    <div className="brand"><b>Omni</b><span>Go</span><b>CRM</b></div><h1>{m?"Create your workspace":"Welcome back"}</h1><p className="muted">{m?"Build your customer operations in one place.":"Sign in to continue to your workspace."}</p>
    {m&&<><label>Name<input required value={f.name} onChange={x=>setF({...f,name:x.target.value})}/></label><label>Workspace<input value={f.workspaceName} onChange={x=>setF({...f,workspaceName:x.target.value})}/></label></>}
    <label>Email<input required type="email" value={f.email} onChange={x=>setF({...f,email:x.target.value})}/></label><label>Password<input required minLength={8} type="password" value={f.password} onChange={x=>setF({...f,password:x.target.value})}/></label>
    {e&&<div className="error">{e}</div>}<button className="primary full">{m?"Create account":"Sign in"}</button><button type="button" className="link" onClick={()=>setM(!m)}>{m?"Already have an account?":"Create a new account"}</button>
  </form></div>;
}

function App(){
  const[token,setToken]=useState(localStorage.getItem("token"));const[user,setUser]=useState(null);const[view,setView]=useState("dashboard");const[search,setSearch]=useState("");const[error,setError]=useState("");
  useEffect(()=>{if(token)api("/auth/me",{},token).then(x=>setUser(x.user)).catch(()=>{localStorage.removeItem("token");setToken(null)})},[token]);
  const logout=()=>{localStorage.removeItem("token");setToken(null);setUser(null)};
  if(!token||!user)return <Login done={setToken}/>;
  return <div className="app-shell"><Sidebar view={view} setView={setView} user={user} logout={logout}/><main className="main"><Topbar search={search} setSearch={setSearch} user={user}/>{error&&<div className="error banner">{error}</div>}{view==="dashboard"?<Dashboard token={token} onNavigate={setView}/>:view==="leads"?<Leads token={token}/>:["calendar","automation","reports","settings"].includes(view)?<ModulePage type={view}/>:<ResourcePage token={token} type={view} search={search} setError={setError}/>}</main></div>;
}

function Sidebar({view,setView,user,logout}){
  return <aside className="sidebar"><div className="brand sidebar-brand"><b>Omni</b><span>Go</span><b>CRM</b></div><div className="workspace-switch"><div className="workspace-avatar">A</div><div><b>{user.name||"Workspace"}</b><small>{user.role||"Owner"}</small></div><span>⌄</span></div><nav>{nav.map(([id,icon,label])=><button key={id} className={view===id?"active":""} onClick={()=>setView(id)}><i>{icon}</i><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><button className="workspace-link">＋ <span>New workspace</span></button><button className="signout" onClick={logout}>↪ <span>Sign out</span></button></div></aside>;
}

function Topbar({search,setSearch,user}){
  return <header className="topbar"><button className="mobile-menu">☰</button><div className="global-search"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search leads, contacts, companies, deals..."/><kbd>⌘ K</kbd></div><div className="top-actions"><button className="circle primary">＋</button><button className="icon-btn">♧<em>3</em></button><button className="icon-btn">?</button><div className="profile"><div className="profile-avatar">{(user.name||"A").slice(0,1).toUpperCase()}</div><div><b>{user.name||"Admin"}</b><small>Workspace</small></div><span>⌄</span></div></div></header>;
}

function PageHead({title,subtitle,actions}){return <div className="page-head"><div><h1>{title}</h1><p>{subtitle}</p></div><div className="page-actions">{actions}</div></div>}

function Dashboard({token,onNavigate}){
  const[d,setD]=useState(null);const[leads,setLeads]=useState([]);const[loading,setLoading]=useState(true);
  useEffect(()=>{Promise.all([api("/dashboard",{},token),api("/leads?limit=5",{},token)]).then(([a,b])=>{setD(a);setLeads(b.data||[])}).finally(()=>setLoading(false))},[token]);
  if(loading)return <section className="content"><div className="loading">Loading dashboard…</div></section>;
  const stats=[["Total Leads",d.leads,"↑ 12%","blue"],["Open Opportunities",d.opportunities,"↑ 24%","purple"],["Pipeline Value",money(d.pipelineValue),"↑ 18%","green"],["Invoices Outstanding","—","This month","orange"],["Tasks Due",d.openTasks,"Due now","red"]];
  return <section className="content"><PageHead title="Dashboard" subtitle="Here's what's happening across your customer operations." actions={<><button className="ghost">Last 30 days⌄</button><button className="primary" onClick={()=>onNavigate("leads")}>＋ Add Lead</button></>}/><div className="stat-grid">{stats.map(([a,b,c,color])=><div className={"metric "+color} key={a}><div className="metric-icon">{a==="Total Leads"?"♙":a==="Open Opportunities"?"◉":a==="Pipeline Value"?"₹":a==="Tasks Due"?"✓":"▧"}</div><div><small>{a}</small><strong>{b}</strong><span>{c}</span></div></div>)}</div><div className="dashboard-grid"><div className="panel revenue"><div className="panel-head"><div><h3>Revenue Overview</h3><p>Monthly revenue performance</p></div><button className="ghost">This year⌄</button></div><div className="chart"><div className="y-axis"><span>₹10L</span><span>₹7.5L</span><span>₹5L</span><span>₹2.5L</span><span>₹0</span></div><div className="chart-area">{[36,52,44,65,58,74,61,82,68,90,78,96].map((h,i)=><div className="bar-wrap" key={i}><div className="bar" style={{height:h+"%"}}></div><span>{["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][i]}</span></div>)}</div></div></div><div className="panel source"><div className="panel-head"><div><h3>Leads by Source</h3><p>Where your leads come from</p></div></div><div className="donut-wrap"><div className="donut"><div><b>{d.leads}</b><small>Total</small></div></div><div className="legend">{[["Website","42%","blue"],["LinkedIn","24%","purple"],["Referral","18%","green"],["Email","10%","orange"],["Other","6%","gray"]].map(x=><div key={x[0]}><i className={x[2]}></i><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></div></div><div className="panel wide"><div className="panel-head"><div><h3>Recent Leads</h3><p>Latest records added to your workspace</p></div><button className="link-btn" onClick={()=>onNavigate("leads")}>View all →</button></div><LeadMiniTable rows={leads}/></div><div className="panel"><div className="panel-head"><div><h3>Upcoming Tasks</h3><p>Keep your team moving</p></div><button className="link-btn" onClick={()=>onNavigate("tasks")}>View all →</button></div><div className="task-list">{["Follow up with new leads","Send proposal to TechCorp","Schedule product demo","Review overdue invoices"].map((x,i)=><div className="task-row" key={x}><div className={"task-check c"+i}>✓</div><div><b>{x}</b><small>{["Today · 10:30 AM","Today · 2:00 PM","Tomorrow · 11:00 AM","Friday · 4:00 PM"][i]}</small></div></div>)}</div></div></div></section>;
}

function LeadMiniTable({rows}){return <div className="mini-table"><div className="mini-head"><span>Name</span><span>Source</span><span>Status</span><span>Owner</span></div>{rows.map(r=><div className="mini-row" key={r.id}><span className="person"><div className="avatar">{(r.first_name||"?").slice(0,1)}{(r.last_name||"").slice(0,1)}</div><b>{r.first_name} {r.last_name||""}</b></span><span><label className="badge source">{title(r.source||"Manual")}</label></span><span><label className={"badge "+(r.status||"new")}>{title(r.status||"New")}</label></span><span>—</span></div>)}</div>}

function Leads({token}){
  const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState("");const[status,setStatus]=useState("");const[selected,setSelected]=useState(null);const[modal,setModal]=useState(false);const[refresh,setRefresh]=useState(0);
  useEffect(()=>{setLoading(true);const q=new URLSearchParams({limit:"10",offset:"0"});if(search)q.set("search",search);if(status)q.set("status",status);api("/leads?"+q.toString(),{},token).then(x=>setRows(x.data||[])).finally(()=>setLoading(false))},[token,search,status,refresh]);
  const totals=useMemo(()=>({total:rows.length,new:rows.filter(x=>(x.status||"new").toLowerCase()==="new").length,qualified:rows.filter(x=>(x.status||"").toLowerCase()==="qualified").length,converted:rows.filter(x=>(x.status||"").toLowerCase()==="converted").length,lost:rows.filter(x=>(x.status||"").toLowerCase()==="lost").length}),[rows]);
  const save=async form=>{await api("/leads",{method:"POST",body:JSON.stringify(form)},token);setModal(false);setRefresh(x=>x+1)};
  return <section className="content"><PageHead title="Leads" subtitle="Manage and track all your leads in one place. Convert more leads into customers." actions={<><button className="ghost">⇩ Export</button><button className="ghost">⇧ Import</button><button className="primary" onClick={()=>setModal(true)}>＋ Add Lead</button></>}/><div className="lead-kpis">{[["Total Leads",totals.total,"↑ 12%","blue"],["New Leads",totals.new,"↑ 18%","green"],["Qualified",totals.qualified,"↑ 24%","purple"],["Converted",totals.converted,"↑ 15%","orange"],["Lost Leads",totals.lost,"↓ 8%","red"]].map(x=><div className={"lead-kpi "+x[3]} key={x[0]}><div className="kpi-icon">◉</div><div><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></div></div>)}</div><div className="filterbar"><div className="table-search">⌕<input placeholder="Search leads..." value={search} onChange={e=>setSearch(e.target.value)}/></div><Select label="Status" value={status} onChange={setStatus} options={["","new","qualified","contacted","proposal","negotiation","converted","lost"]}/><Select label="Source" options={["","website","linkedin","referral","email","facebook","manual"]}/><Select label="Owner" options={[""]}/><Select label="Created At" options={["","Last 30 days","This month","This year"]}/><button className="ghost filter-btn">☷ Filters</button></div><div className="bulkbar"><input type="checkbox"/><button>✉ Send Email</button><button>◉ Send WhatsApp</button><button>♙ Assign</button><button>₹ Convert to Opportunity</button><button>⊙ More⌄</button><span>{rows.length?"1–"+Math.min(10,rows.length)+" of "+rows.length:"0 records"} <button>‹</button><button>›</button></span></div><div className="leads-layout"><div className="panel lead-table-panel">{loading?<div className="loading">Loading leads…</div>:<div className="lead-table"><div className="lead-head"><span>□</span><span>Name</span><span>Company</span><span>Email</span><span>Phone</span><span>Source</span><span>Status</span><span>Owner</span><span>Created At</span><span>Actions</span></div>{rows.map(r=><LeadRow key={r.id} row={r} onOpen={()=>setSelected(r)}/>)}</div>}{!loading&&!rows.length&&<div className="empty">No leads found. Try another filter or add your first lead.</div>}</div>{selected&&<LeadDetail token={token} lead={selected} close={()=>setSelected(null)} onChanged={()=>{setSelected(null);setRefresh(x=>x+1)}}/>}</div>{modal&&<LeadModal close={()=>setModal(false)} save={save}/>}</section>;
}

function Select({label,value="",onChange=()=>{},options=[]}){return <label className="filter-select"><small>{label}</small><select value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option value={x} key={x}>{x?title(x):"All "+label+"s"}</option>)}</select></label>}

function LeadRow({row,onOpen}){return <div className="lead-row" onClick={onOpen}><span>□</span><span className="person"><div className="avatar">{(row.first_name||"?").slice(0,1)}{(row.last_name||"").slice(0,1)}</div><b>{row.first_name} {row.last_name||""}</b></span><span>{row.company||"—"}</span><span>{row.email||"—"}</span><span>{row.phone||"—"}</span><span><label className="badge source">{title(row.source||"manual")}</label></span><span><label className={"badge "+(row.status||"new")}>{title(row.status||"new")}</label></span><span><div className="owner-dot">—</div></span><span>{formatDate(row.created_at)}</span><span>•••</span></div>}

function LeadDetail({token,lead,close,onChanged}){
  const[l,setL]=useState(lead);const[tab,setTab]=useState("Overview");const[edit,setEdit]=useState(false);const[busy,setBusy]=useState(false);
  useEffect(()=>{api("/leads/"+lead.id,{},token).then(x=>setL(x.data)).catch(()=>{})},[lead.id,token]);
  const update=async form=>{setBusy(true);try{const r=await api("/leads/"+l.id,{method:"PATCH",body:JSON.stringify(form)},token);setL(r.data);setEdit(false);onChanged()}finally{setBusy(false)}};
  return <aside className="lead-detail"><div className="detail-top"><button className="close" onClick={close}>×</button><div className="detail-person"><div className="big-avatar">{(l.first_name||"?").slice(0,1)}{(l.last_name||"").slice(0,1)}</div><div><h2>{l.first_name} {l.last_name||""}</h2><p>{l.job_title||"Lead"} <span>·</span> {l.company||"No company"}</p></div><label className={"badge "+(l.status||"new")}>{title(l.status||"new")}</label></div><div className="detail-actions"><button className="ghost" onClick={()=>setEdit(true)}>✎ Edit</button><button className="primary">₹ Convert</button><button className="ghost">•••</button></div></div><div className="detail-meta"><span>✉ <a>{l.email||"No email"}</a></span><span>⌕ {l.phone||"No phone"}</span><span>◎ {title(l.source||"manual")}</span></div><div className="detail-score"><div><small>Lead Score</small><strong>★★★★☆ <b>80</b></strong></div><div><small>Status</small><label className={"badge "+(l.status||"new")}>{title(l.status||"new")}</label></div><div><small>Created</small><b>{formatDate(l.created_at)}</b></div><div><small>Last Contacted</small><b>—</b></div></div><div className="tabs">{["Overview","Activity","WhatsApp","Notes","Emails","Tasks","Files","Automation","Related Records"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==="Overview"?<div className="detail-body"><DetailCard title="Contact Information" edit={()=>setEdit(true)} items={[["First Name",l.first_name],["Last Name",l.last_name],["Email",l.email],["Phone",l.phone],["Job Title",l.job_title],["Company",l.company],["Website",l.website],["Location",l.location]]}/><DetailCard title="Lead Details" edit={()=>setEdit(true)} items={[["Status",title(l.status||"new")],["Source",title(l.source||"manual")],["Expected Value","—"],["Expected Close Date","—"],["Industry","—"],["Tags","B2B · Website"],["Description","Interested in your products and services."]]}/><WhatsAppComposer token={token} lead={l}/><div className="detail-card"><div className="card-title"><h3>Recent Activity</h3><button className="link-btn">View all</button></div><div className="activity"><Activity icon="✉" title="Lead created" text="Lead was added to your workspace" time={formatDate(l.created_at)}/><Activity icon="✓" title="Status checked" text={"Current status: "+title(l.status||"new")} time="Today"/></div></div></div>:tab==="WhatsApp"?<div className="detail-body"><WhatsAppComposer token={token} lead={l}/></div>:<div className="tab-empty"><div>{tab==="Activity"?"◷":"✦"}</div><h3>{tab}</h3><p>{tab} timeline and records will appear here as your workspace activity grows.</p></div>}{edit&&<EditLead lead={l} close={()=>setEdit(false)} save={update} busy={busy}/>}</aside>;
}

function WhatsAppComposer({token,lead}){
  const[templates,setTemplates]=useState([]);const[assets,setAssets]=useState([]);const[templateId,setTemplateId]=useState("");const[assetId,setAssetId]=useState("");const[body,setBody]=useState("");const[mode,setMode]=useState("auto");const[busy,setBusy]=useState(false);const[notice,setNotice]=useState("");const[error,setError]=useState("");
  useEffect(()=>{Promise.all([api("/whatsapp/templates?channel=whatsapp",{},token),api("/whatsapp/assets",{},token)]).then(([t,a])=>{setTemplates(t.data||[]);setAssets(a.data||[])}).catch(e=>setError(e.message))},[token]);
  const selectedAsset=assets.find(x=>x.id===assetId);const selectedTemplate=templates.find(x=>x.id===templateId);
  const chooseTemplate=id=>{setTemplateId(id);const t=templates.find(x=>x.id===id);if(t){setBody(t.body||"");setAssetId(t.media_asset_id||"")}};
  const personalize=v=>String(v||"").replaceAll("{first_name}",lead.first_name||"").replaceAll("{last_name}",lead.last_name||"").replaceAll("{name}",[lead.first_name,lead.last_name].filter(Boolean).join(" "));
  const send=async()=>{setError("");setNotice("");if(!lead.phone){setError("This lead does not have a phone number.");return}if(!body.trim()){setError("Write a message or choose a template first.");return}setBusy(true);try{const r=await api("/leads/"+lead.id+"/whatsapp/prepare",{method:"POST",body:JSON.stringify({body,template_id:templateId||undefined,media_asset_id:assetId||undefined})},token);setNotice("Opening WhatsApp…");const isMobile=/Android|iPhone|iPad|iPod/i.test(navigator.userAgent);const url=mode==="desktop"?r.urls.desktop:mode==="web"?r.urls.web:mode==="mobile"?r.urls.mobile:(isMobile?r.urls.mobile:r.urls.web);window.location.href=url}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="detail-card whatsapp-composer"><div className="card-title"><div><h3>WhatsApp Composer</h3><p className="composer-help">Prepare a message for this lead, then continue in WhatsApp.</p></div><span className="wa-badge">WhatsApp</span></div><div className="composer-grid"><label>Message template<select value={templateId} onChange={e=>chooseTemplate(e.target.value)}><option value="">Write a custom message</option>{templates.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>WhatsApp destination<select value={mode} onChange={e=>setMode(e.target.value)}><option value="auto">Auto detect device</option><option value="web">WhatsApp Web</option><option value="desktop">WhatsApp Desktop</option><option value="mobile">WhatsApp mobile app</option></select></label></div><label className="composer-message">Message<textarea rows="5" value={personalize(body)} onChange={e=>setBody(e.target.value)} placeholder={"Hi "+(lead.first_name||"there")+", I wanted to share an update with you."}/></label><div className="media-picker"><div><b>Media asset</b><small>Attach a predefined asset by adding its public link to the WhatsApp message.</small></div><select value={assetId} onChange={e=>setAssetId(e.target.value)}><option value="">＋ Add media asset…</option>{assets.map(a=><option value={a.id} key={a.id}>{a.name} · {title(a.asset_type)}</option>)}</select></div>{selectedAsset&&<div className="selected-asset"><span>📎</span><div><b>{selectedAsset.name}</b><small>{selectedAsset.description||selectedAsset.url}</small></div><button type="button" onClick={()=>setAssetId("")}>Remove</button></div>}{error&&<div className="error composer-error">{error}</div>}{notice&&<div className="composer-notice">{notice}</div>}<div className="composer-actions"><span className="composer-phone">{lead.phone?"To: "+lead.phone:"No phone number"}</span><button className="primary whatsapp-send" disabled={busy||!lead.phone} onClick={send}>{busy?"Opening…":"Send WhatsApp ↗"}</button></div><p className="composer-footnote">The CRM opens a pre-filled WhatsApp chat. You still tap Send inside WhatsApp. On mobile, WhatsApp decides whether Personal or Business handles the link when both are installed.</p></div>;
}
function DetailCard({title:heading,items,edit}){return <div className="detail-card"><div className="card-title"><h3>{heading}</h3><button className="edit-link" onClick={edit}>✎ Edit</button></div><div className="detail-fields">{items.map(([k,v])=><div key={k}><small>{k}</small><span>{v||"—"}</span></div>)}</div></div>}
function Activity({icon,title:heading,text,time}){return <div className="activity-row"><i>{icon}</i><div><b>{heading}</b><p>{text}</p></div><small>{time}</small></div>}
function LeadModal({close,save}){return <LeadForm title="Add Lead" close={close} save={save}/>}
function EditLead({lead,close,save,busy}){return <LeadForm title="Edit Lead" close={close} save={save} initial={lead} busy={busy}/>}
function LeadForm({title:heading,close,save,initial={},busy=false}){
  const[f,setF]=useState({first_name:initial.first_name||"",last_name:initial.last_name||"",email:initial.email||"",phone:initial.phone||"",source:initial.source||"manual",status:initial.status||"new"});
  const submit=e=>{e.preventDefault();save(f)};return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><h2>{heading}</h2><p>Capture the customer information your team needs.</p></div><button type="button" className="close" onClick={close}>×</button></div><div className="form-grid"><label>First name<input required value={f.first_name} onChange={e=>setF({...f,first_name:e.target.value})}/></label><label>Last name<input value={f.last_name} onChange={e=>setF({...f,last_name:e.target.value})}/></label><label>Email<input type="email" value={f.email} onChange={e=>setF({...f,email:e.target.value})}/></label><label>Phone<input value={f.phone} onChange={e=>setF({...f,phone:e.target.value})}/></label><label>Source<select value={f.source} onChange={e=>setF({...f,source:e.target.value})}>{["manual","website","linkedin","referral","email","facebook"].map(x=><option key={x}>{x}</option>)}</select></label><label>Status<select value={f.status} onChange={e=>setF({...f,status:e.target.value})}>{["new","qualified","contacted","proposal","negotiation","converted","lost"].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="modal-actions"><button type="button" className="ghost" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy?"Saving…":"Save Lead"}</button></div></form></div>;
}
function ModulePage({type}){const config={calendar:["Calendar","Plan meetings, follow-ups and your team schedule."],automation:["Automation","Build triggers, actions and customer workflows."],reports:["Reports","Understand pipeline performance, revenue and team activity."],settings:["Settings","Configure your workspace, users and integrations."]}[type]||[title(type), "Manage your workspace."];return <section className="content"><PageHead title={config[0]} subtitle={config[1]} actions={<button className="primary">＋ Create</button>}/><div className="module-grid"><div className="panel module-hero"><div className="module-icon">✦</div><h2>{config[0]}</h2><p>{config[1]}</p><button className="primary">Get started</button></div><div className="panel module-list"><h3>Workspace overview</h3>{["Activity","Assignments","Notifications","Integrations"].map(x=><div className="module-item" key={x}><span>{x}</span><b>Coming online</b></div>)}</div></div></section>}
function ResourcePage({token,type,search,setError}){
  const[label]=resourceMap[type]||[title(type),title(type.slice(0,-1))];const[rows,setRows]=useState([]);const[loading,setLoading]=useState(true);
  useEffect(()=>{setLoading(true);api("/"+type+"?limit=50"+(search?"&search="+encodeURIComponent(search):""),{},token).then(x=>setRows(x.data||[])).catch(x=>setError(x.message)).finally(()=>setLoading(false))},[type,token,search,setError]);
  return <section className="content"><PageHead title={label} subtitle={"Manage your "+label.toLowerCase()+" and keep your team aligned."} actions={<button className="primary">＋ Add {resourceMap[type]?.[1]||"Record"}</button>}/><div className="toolbar-card"><div className="table-search">⌕<input placeholder={"Search "+label.toLowerCase()+"..."} value={search} readOnly/></div><button className="ghost">☷ Filters</button></div><div className="panel table-panel">{loading?<div className="loading">Loading…</div>:<GenericTable rows={rows}/>}</div></section>;
}
function GenericTable({rows}){if(!rows.length)return <div className="empty">No records yet.</div>;const cols=Object.keys(rows[0]).filter(k=>k!=="workspace_id").slice(0,8);return <div className="generic-table"><div className="generic-head">{cols.map(k=><span key={k}>{title(k.replaceAll("_"," "))}</span>)}</div>{rows.map(r=><div className="generic-row" key={r.id}>{cols.map(k=><span key={k}>{String(r[k]??"—").slice(0,80)}</span>)}</div>)}</div>}
function money(v){return "₹"+Number(v||0).toLocaleString("en-IN")}
function title(v){return String(v).replaceAll("_"," ").replace(/\b\w/g,x=>x.toUpperCase())}
function formatDate(v){if(!v)return "—";return new Date(v).toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"})}
createRoot(document.getElementById("root")).render(<React.StrictMode><App/></React.StrictMode>);
