@extends('layouts.app') @section('title','· Lead') @section('content')
<div class="page-head"><div><h1>{{ $lead->first_name }} {{ $lead->last_name }}</h1><p class="muted">{{ $lead->company ?: 'Individual lead' }} · {{ $lead->mobile }}</p></div><div class="actions">@if($lead->mobile)<a class="btn primary" target="_blank" href="https://wa.me/{{ preg_replace('/\D+/','',$lead->whatsapp ?: $lead->mobile) }}">WhatsApp</a>@endif @if($lead->converted_contact_id)<a class="btn" href="{{ route('contacts.show',$lead->converted_contact_id) }}">Open Contact</a>@else<form method="POST" action="{{ route('leads.convert',$lead) }}">@csrf<button class="btn">Convert to Contact</button></form>@endif</div></div>
<div class="two-col"><section class="panel"><h2>Lead details</h2><div class="detail-grid"><span>Mobile</span><strong>{{ $lead->mobile }}</strong><span>WhatsApp</span><strong>{{ $lead->whatsapp ?: '—' }}</strong><span>Email</span><strong>{{ $lead->email ?: '—' }}</strong><span>Source</span><strong>{{ $lead->source ?: '—' }}</strong><span>Status</span><strong>{{ $lead->status }}</strong><span>Owner</span><strong>{{ $lead->assignee?->name ?: 'Unassigned' }}</strong></div><hr><p><b>Requirement:</b> {{ $lead->requirement ?: '—' }}</p><p><b>Notes:</b> {{ $lead->notes ?: '—' }}</p></section>
<section class="panel"><h2>WhatsApp message templates</h2><p class="muted">Choose a situation, then open WhatsApp with the pre-filled message.</p><select id="templateSelect"><option value="">Select situation</option>@foreach($templates->unique('situation') as $t)<option value="{{ $t->id }}">{{ ucwords(str_replace('_',' ',$t->situation)) }}</option>@endforeach</select><textarea id="preview" placeholder="Template preview will appear here"></textarea><button id="waBtn" class="btn primary" disabled>Open WhatsApp</button></section></div>
<section class="panel"><h2>Calls</h2><table><thead><tr><th>Date</th><th>Phone</th><th>Direction</th><th>Duration</th><th>Recording</th></tr></thead><tbody>@forelse($lead->calls as $call)<tr><td>{{ $call->called_at }}</td><td>{{ $call->phone }}</td><td>{{ $call->direction }}</td><td>{{ $call->durationLabel() }}</td><td>@if($call->recording_path && in_array(request()->attributes->get('crmUser')->role,['admin','super_admin']))<a href="{{ route('calls.recording',$call) }}" target="_blank">Play</a>@elseif($call->recording_path)<span class="muted">Admin only</span>@else>—@endif</td></tr>@empty<tr><td colspan="5">No calls logged.</td></tr>@endforelse</tbody></table></section>
@endsection
@push('scripts')
<script>const templates=@json($templates->groupBy('situation'));const lead=@json(['mobile'=>$lead->whatsapp?:$lead->mobile]);const sel=document.getElementById('templateSelect'),prev=document.getElementById('preview'),btn=document.getElementById('waBtn');function fill(t){return t.replaceAll('{first_name}',@json($lead->first_name)).replaceAll('{last_name}',@json($lead->last_name??'')).replaceAll('{company}',@json($lead->company??'')).replaceAll('{requirement}',@json($lead->requirement??'')).replaceAll('{salesperson}',@json(request()->attributes->get('crmUser')->name)).replaceAll('{company_name}',@json(config('app.company_name')));}sel.addEventListener('change',()=>{const t=[...templates].flatMap(x=>x[1]).find(x=>String(x.id)===sel.value);prev.value=t?fill(t.body):'';btn.disabled=!t;btn.onclick=()=>window.open('https://wa.me/'+lead.mobile.replace(/\D/g,'')+'?text='+encodeURIComponent(prev.value),'_blank');});</script>
@endpush
