<?php
use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
return new class extends Migration{
public function up():void{
Schema::create('workspaces',function(Blueprint $t){$t->id();$t->string('name');$t->string('slug')->unique();$t->string('plan')->default('trial');$t->string('status')->default('active');$t->dateTime('trial_ends_at')->nullable();$t->timestamps();});
Schema::create('companies',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('email')->nullable();$t->string('phone',30)->nullable();$t->text('address')->nullable();$t->string('website')->nullable();$t->string('status')->default('active');$t->timestamps();$t->index(['workspace_id','name']);});
Schema::create('tags',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('name');$t->string('color',20)->default('#2563eb');$t->unique(['workspace_id','name']);});
Schema::create('lead_tag',function(Blueprint $t){$t->foreignId('lead_id')->constrained('leads')->cascadeOnDelete();$t->foreignId('tag_id')->constrained()->cascadeOnDelete();$t->primary(['lead_id','tag_id']);});
Schema::create('tasks',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('assigned_to')->nullable()->constrained('users')->nullOnDelete();$t->morphs('subject');$t->string('title');$t->text('description')->nullable();$t->dateTime('due_at')->nullable();$t->string('priority',20)->default('normal');$t->string('status',20)->default('open')->index();$t->timestamps();});
Schema::create('activity_logs',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('user_id')->nullable()->constrained('users')->nullOnDelete();$t->morphs('subject');$t->string('action',50);$t->text('description')->nullable();$t->json('meta')->nullable();$t->ipAddress('ip_address')->nullable();$t->timestamps();});
Schema::create('orders',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->string('order_number')->unique();$t->string('status',30)->default('pending');$t->decimal('subtotal',14,2)->default(0);$t->decimal('tax',14,2)->default(0);$t->decimal('total',14,2)->default(0);$t->date('order_date')->nullable();$t->timestamps();});
Schema::create('payments',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->foreignId('customer_id')->nullable()->constrained()->nullOnDelete();$t->foreignId('order_id')->nullable()->constrained()->nullOnDelete();$t->string('reference')->nullable();$t->decimal('amount',14,2);$t->string('method',30)->default('cash');$t->dateTime('paid_at');$t->string('status',20)->default('received');$t->text('notes')->nullable();$t->timestamps();});
Schema::create('custom_fields',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->constrained()->cascadeOnDelete();$t->string('entity',30);$t->string('field_key',80);$t->string('label');$t->string('field_type',20)->default('text');$t->text('options')->nullable();$t->boolean('required')->default(false);$t->timestamps();$t->unique(['workspace_id','entity','field_key']);});
Schema::create('workspace_subscriptions',function(Blueprint $t){$t->id();$t->foreignId('workspace_id')->unique()->constrained()->cascadeOnDelete();$t->string('plan')->default('trial');$t->string('status')->default('trialing');$t->dateTime('starts_at');$t->dateTime('ends_at')->nullable();$t->string('provider')->nullable();$t->string('external_id')->nullable();$t->timestamps();});
Schema::table('users',function(Blueprint $t){$t->foreignId('workspace_id')->nullable()->constrained('workspaces')->nullOnDelete();});
foreach(['leads','contacts','customers','message_templates','follow_ups','calls','products','quotations'] as $table)Schema::table($table,function(Blueprint $t){$t->foreignId('workspace_id')->nullable()->constrained('workspaces')->nullOnDelete();});
}
public function down():void{Schema::dropIfExists('workspace_subscriptions');Schema::dropIfExists('custom_fields');Schema::dropIfExists('payments');Schema::dropIfExists('orders');Schema::dropIfExists('activity_logs');Schema::dropIfExists('tasks');Schema::dropIfExists('lead_tag');Schema::dropIfExists('tags');Schema::dropIfExists('companies');}
};