apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omnigocrm-data
  namespace: omnigocrm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: omnigocrm-db
  namespace: omnigocrm
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
