<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use App\Models\Lead;
use App\Models\Contact;
use App\Models\Customer;
use App\Models\FollowUp;
use App\Models\MessageTemplate;
use App\Models\Call;
use Illuminate\Http\Request;
class CrmApiController extends Controller {
 private function user(Request $r){return $r->attributes->get('apiUser');}
 public function dashboard(Request $r){$u=$this->user($r);$q=Lead::query();if($u->role==='sales')$q->where('assigned_to',$u->id);return ['counts'=>['leads'=>(clone $q)->count(),'contacts'=>Contact::count(),'customers'=>Customer::count(),'followups'=>FollowUp::where('status','pending')->whereDate('scheduled_for','<=',now()->endOfDay())->count()],'recent_leads'=>(clone $q)->latest()->limit(10)->get()];}
 public function leads(Request $r){$q=Lead::with('assignee')->latest();if($r->filled('search')){$s=$r->string('search')->toString();$q->where(fn($x)=>$x->where('first_name','like',"%$s%")->orWhere('last_name','like',"%$s%")->orWhere('mobile','like',"%$s%")->orWhere('company','like',"%$s%"));}if(($u=$this->user($r))->role==='sales')$q->where('assigned_to',$u->id);return $q->paginate(20);}
 public function storeLead(Request $r){$u=$this->user($r);$d=$r->validate(['first_name'=>'required|max:100','last_name'=>'nullable|max:100','company'=>'nullable|max:150','email'=>'nullable|email','mobile'=>'required|max:30','whatsapp'=>'nullable|max:30','source'=>'nullable|max:100','status'=>'nullable|max:40','requirement'=>'nullable','notes'=>'nullable','assigned_to'=>'nullable|exists:users,id']);$d['created_by']=$u->id;if($u->role==='sales')$d['assigned_to']=$u->id;$d['status']=$d['status']??'new';return response()->json(['lead'=>Lead::create($d)],201);}
 public function lead(Lead $lead,Request $r){$u=$this->user($r);if($u->role==='sales' && (int)$lead->assigned_to!==(int)$u->id)return response()->json(['message'=>'Forbidden'],403);return ['lead'=>$lead->load(['assignee','followUps'])];}
 public function convertLead(Lead $lead,Request $r){if($lead->converted_contact_id)return response()->json(['message'=>'Already converted'],422);$c=Contact::create(['first_name'=>$lead->first_name,'last_name'=>$lead->last_name,'company'=>$lead->company,'email'=>$lead->email,'mobile'=>$lead->mobile,'whatsapp'=>$lead->whatsapp,'notes'=>$lead->notes,'source_lead_id'=>$lead->id]);$lead->update(['converted_contact_id'=>$c->id,'status'=>'converted']);return ['contact'=>$c,'lead'=>$lead];}
 public function contacts(){return Contact::with('customer')->latest()->paginate(20);}
 public function contact(Contact $contact){return ['contact'=>$contact->load(['customer','followUps'])];}
 public function convertContact(Contact $contact){if($contact->customer)return ['customer'=>$contact->customer];$c=Customer::create(['contact_id'=>$contact->id,'customer_code'=>'CUS-'.str_pad((string)$contact->id,6,'0',STR_PAD_LEFT)]);return response()->json(['customer'=>$c->load('contact')],201);}
 public function customers(){return Customer::with('contact')->latest()->paginate(20);}
 public function customer(Customer $customer){return ['customer'=>$customer->load(['contact','quotations'])];}
 public function templates(Request $r){$q=MessageTemplate::where('active',true)->orderBy('situation')->orderBy('name');if($r->filled('situation'))$q->where('situation',$r->string('situation'));return $q->get();}
 public function whatsapp(string $type,int $id,Request $r){$e=match($type){'lead'=>Lead::findOrFail($id),'contact'=>Contact::findOrFail($id),'customer'=>Customer::with('contact')->findOrFail($id),default=>abort(404)};if($type==='customer')$e=$e->contact;$t=MessageTemplate::where('active',true)->when($r->filled('situation'),fn($q)=>$q->where('situation',$r->string('situation')))->first();if(!$t)return response()->json(['message'=>'No active template'],422);$phone=preg_replace('/\D+/','',$e->whatsapp ?: $e->mobile ?: '');if(str_starts_with($phone,'0'))$phone='91'.substr($phone,1);if(!str_starts_with($phone,'91'))$phone='91'.$phone;$body=strtr($t->body,['{first_name}'=>$e->first_name,'{last_name}'=>$e->last_name??'','{company}'=>$e->company??'','{requirement}'=>$e->requirement??'','{salesperson}'=>$this->user($r)->name,'{company_name}'=>config('app.name'),'{phone}'=>$phone]);return ['url'=>'https://wa.me/'.$phone.'?text='.rawurlencode($body),'message'=>$body,'phone'=>$phone];}
 public function followUps(Request $r){$q=FollowUp::with(['subject','assignee'])->latest('scheduled_for');if($r->filled('status'))$q->where('status',$r->string('status'));return $q->paginate(30);}
 public function storeFollowUp(Request $r){$u=$this->user($r);$d=$r->validate(['subject_type'=>'required|in:lead,contact,customer','subject_id'=>'required|integer','scheduled_for'=>'required|date','type'=>'nullable|max:40','note'=>'nullable']);$map=['lead'=>Lead::class,'contact'=>Contact::class,'customer'=>Customer::class];$d['subject_type']=$map[$d['subject_type']];$d['assigned_to']=$u->id;$d['status']='pending';return response()->json(FollowUp::create($d),201);}
 public function storeCall(Request $r){$u=$this->user($r);$d=$r->validate(['subject_type'=>'required|in:lead,contact,customer','subject_id'=>'required|integer','phone'=>'required|max:30','duration_seconds'=>'nullable|integer|min:0','status'=>'nullable|max:30','direction'=>'nullable|max:20','called_at'=>'nullable|date']);$map=['lead'=>Lead::class,'contact'=>Contact::class,'customer'=>Customer::class];$d['subject_type']=$map[$d['subject_type']];$d['user_id']=$u->id;$d['called_at']=$d['called_at']??now();return response()->json(Call::create($d),201);}
 public function uploadRecording(Request $r,Call $call){$r->validate(['recording'=>'required|file|max:51200|mimes:m4a,mp3,wav,3gp,amr,ogg']);$file=$r->file('recording');$path=$file->store('call-recordings/'.now()->format('Y/m'),'local');$call->update(['recording_path'=>$path,'recording_name'=>$file->getClientOriginalName(),'recording_size'=>$file->getSize()]);return ['message'=>'Recording uploaded','call'=>$call];}
}
